### ISSUE TITLE
Add support for message exchange patterns such as request-reply

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/spec#558]
Currently, AsyncAPI models individual message types exchanged via operations with channels. There is no way to formally bind different messages together (other than by adding human-readable documentation to the messages).

For example, currently this common message exchange pattern cannot be expressed in AsyncAPI documents:
- A client application sends request messages with a unique message ID to channel 1
- and expects response messages with a correlation ID equal to the request message ID on another channel 2

Or this variation thereof:
- A client application sends request messages with a unique message ID and a reply channel to channel 1
- and expects response messages with a correlation ID equal to the request message ID on that reply channel

In these examples, in an AsyncAPI document, the relationship between request and reply messages and their header/payload values for message ID, correlation ID, and reply channel cannot be expressed.

This RFC is about adding support for higher-level message exchange patterns of this kind to AsyncAPI. See also https://www.enterpriseintegrationpatterns.com/patterns/conversation/BasicIntro.html

**Comment by derberg** [comment]
might be related with https://github.com/asyncapi/spec/issues/94

**Comment by crussell52** [comment]
Most of the async work I do is request-response. Is there anything community members like me can do to help advance this?

**Comment by derberg** [comment]
@crussell52 definitely, have a look at the contribution guide that explains the spec contribution stages. Also, look at the related issue that I linked before, where few people already shared possible solutions. Definitely feel free to suggest solutions with proper examples.

**Comment by olamiral-mulesoft** [comment]
@GeraldLoeffler Could you please take a look at [my comment] (https://github.com/asyncapi/spec/issues/618#issuecomment-974603269) on #618. I'd like to hear from you and see how we can evolve the proposed model in order to support your requirements. Thank you!

**Comment by olamiral** [comment]
@GeraldLoeffler Could you please take a look at my comment. I'd like to hear from you and see how we can evolve the proposed model in order to support your requirements. Thank you!

**Comment by jonaslagoni** [comment]
Is there any of you who wants to champion this? 🙂 Or can we consider this issue as needs champion? 🤔

**Comment by Hassen-BENNOUR** [comment]
Hi folks, 
Unfortunately it seems to need many time to find the right solution. 

We have many amqp request reply communication between services as many people today.
We do it with spring integration and spring cloud stream. 
Without support of request reply i think there is no reason or possibility to use asyncapi now 😔

Keep in touch and hope a support for this soon.

So thank you for your amazing stuff.

**Comment by jfallows** [comment]
> @GeraldLoeffler Could you please take a look at [my comment](https://github.com/asyncapi/spec/issues/618#issuecomment-974603269)? I'd like to hear from you and see how we can evolve the proposed model in order to support your requirements. Thank you!

@olamiral did you get any response perhaps in another forum about your question and feedback?

**Comment by olamiral-mulesoft** [comment]
@jfallows Not yet. I saw there were some discussions around the spec in issue #520, but I'm not sure if we could come to a conclusion about it yet. 

Regarding how messages / events could be tracked and related to each other, one option would be defining a message as an entity composed by:
- a section for tracking / correlation: list of fields that will be used to track the message. Correlation can be made at several contexts: 
  - request context: would primarily be used to correlate replies and events to the corresponding request
  - transaction context: set of operations required to fulfill a request / transaction
  - session context: set of transactions that can be executed in a given session.
- a section for metadata / headers: list of fields containing metadata (except tracking / correlation information). Technically, correlation identifiers could go in the headers section of the message, but it's important to make a clear distinction between tracking metadata and other metadata at least at the spec level because it explicitly states which fields should be used for message tracking / correlation)
- a section for message body / payload: business data used in operations requests / replies or to describe events.

@GeraldLoeffler has a very good point, and the spec should take this into account (for standardization and documentation at spec level, avoiding relying on human readable docs only).

**Comment by jonaslagoni** [comment]
Can someone close this issue as complete?

**Comment by derberg** [comment]
closing as already done
details https://eventstack.tech/posts/asyncapi-v3-request-reply
will be released with v3 soon
