### ISSUE TITLE
Questions about the spec: how to connect channel to server and how to use the security schemas

### ISSUE THREAD

**Issue by cdavernas** [asyncapi/spec#578]
Hello everyone!

First of all, big up for your incredible work, which we are starting to implement in CNCF's Serverless Workflow, and for which I already created a .NET 5.0 parser, generator, fluent builder and code-first generator. [Check it out](https://github.com/neuroglia-io/AsyncApi)

Second, I got dumb some questions I could not find any answer to by crawling the usual channels, so here I am:

1. How should servers be selected for particular bindings? Say I have an operation with a Kafka binding, another one with a NATS binding, how should I automatically select the adequate server for the NATS one? Checking the one that declares a NATS binding, I guess, right? If so, what happens in case I have multiple servers that declare one? Should I go round Robin on them? What about servers with no declared bindings?
2. The spec declares many security schemes, and that's great, but there very little on their specifics and how they should be used. For example, for an HTTP server, what are my options? Can I use ApiKey or HttpApiKey? What are the differences? What should I do with settings like `in: user`? A mapping of protocol / related security schemes would be pure gold. As would a couple of practical examples on each of the proposed scheme. Are those info available?

Thanks in advance for your time and patience!

**Comment by magicmatatjahu** [comment]
@cdavernas HI! Thanks for your issue and kindly first thoughts 🤗 

I don't want to answer fo the second question, because I'm not the expert for security at all and I don't want to tell to you untruth about spec/security. I hope that someone from community answer for that in the nearest future - you can ask for that in our slack (https://asyncapi.slack.com/join/shared_invite/enQtNDY3MzI0NjU5OTQyLTM5NTlkYzFmZDQyMGVkNzVkOTRhMGU2N2VmMWRlOTdkNWE0YzdjMGQ2NzRlOWU1NGJkYjUyZDEzMzM3ZGYzYzM)

But for the first: I see your problem and we have several opened issues for that like:
- https://github.com/asyncapi/spec/issues/255
- https://github.com/asyncapi/spec/issues/244 (topics is an old name for the channels, used in 1.X.X spec)

and we have one PR opened for connecting the given channel to server(s) - https://github.com/asyncapi/spec/pull/531

...so at the moment is very hard to connect given channel to the given server. We also don't know when we put to the spec the proposal from https://github.com/asyncapi/spec/pull/531 (btw. which is cool, because you operate on reference to the given server) - maybe in the next release which is scheduled at the end of September.

If you have only one server with given server, it's easy to connect channels (as you wrote), but for the multiple servers as you see we haven't any way to connect them, but I see some workaround:
- check the config from server binding with given channel binding and connect them - very problematic solution, in some protocols you can connect channel with server by the `queue` name - of course if that config exists in protocol
- use the extensions in channel like `x-connected-server`:

```yaml
servers:
  someNatsServer:
    ...
    
channels:
   someChannel:
      x-connected-server: someNatsServer
```

but it's not a good idea, because currently we are on investigation of extensions - how to create them, distribute etc, so extensions are in the "alpha" stage.

And the last thing, servers without any defined bindings - you should treat them as server with default configuration for given protocol :)

**Comment by cdavernas** [comment]
@magicmatatjahu Thanks for the info! I guess I should have taken a deeper look into existing issues indeed. Sorry about that.

As for security, let's hope someone can give me some directions on how to proceed 😄

**Comment by fmvilas** [comment]
Hey @cdavernas! Let me reply to some of your questions the best I can:

> for an HTTP server, what are my options?

All the security mechanisms that the HTTP protocol support: Basic, Bearer, HTTP API key, OAuth2, and OpenID Connect.

> Can I use ApiKey or HttpApiKey?

If your server is an HTTP server, better to use HttpApiKey.

> What are the differences?

`ApiKey` is meant for those protocols that don't support passing just an API key. To "fake it", many providers tell you to pass the API key in the `user` field of a user/password auth type. They often recommend leaving the password empty for such cases. However, the opposite also exists. Leave the user empty and use the password field for the API key. That's why you see `in: user` or `in: password`.

In the case of `HttpKey`, the `in` field can be either `query`, `headers`, or `cookie`. It tells the system where to find the API key.

> A mapping of protocol / related security schemes would be pure gold. As would a couple of practical examples on each of the proposed scheme. Are those info available?

There's nothing like that and I agree this would be gold. If you find the time while you're learning, it would be awesome to get it contributed. I'll be happy to assist you as needed.

**Comment by derberg** [comment]
Looking at detailed answers and 👍🏼 from @cdavernas I assume all questions are answered, thus closing. Feel free to reopen in case I'm wrong 😅

**Comment by cdavernas** [comment]
@derberg All 1uestions answered indeed, many thanks!!!
