### ISSUE TITLE
Unable to specify '>' wildcard semantics in a channel object

### ISSUE THREAD

**Issue by gregmeldrum** [asyncapi/spec#587]
### Describe the bug
The format of the channel is based on URI templates for which the '>' character is a forbidden character. The '>' character is used by some brokers as a wildcard character to match one or more topic levels. There is no suitable variable replacement in the channel that matches the semantics of the `>` character. For instance, a subscription of `mychannel/*` character could be represented by the channel `mychannel/{all}` where {all} specifies all potential values. The semantics of the `>` character would require a potentially infinite number of channels. For instance, a subscription of `mychannel/>` would match channels `mychannel/{all}` and `mychannel/{all}/{all}` and so on.

### To Reproduce
Use a `>` character in the channel

### Expected behavior
Either provide the ability to use the > character in the channel (this would be very useful for documentation and code-generation) or provide an alternative mechanism to represent the semantics of matching one or more levels in a channel.

### Additional context
Based on this slack conversation: https://asyncapi.slack.com/archives/C0230UAM6R3/p1626958304195900

**Comment by jonaslagoni** [comment]
I had the same use case as you, and I am just gonna leave the approach I adopted (by using parameters):
```yaml
asyncapi: 2.1.0
info:
  title: test
  version: 0.0.1
channels: 
  mytopic/{all}:
    parameters:
      all:
        description: All wildcard
        schema: 
          const: ">"
    subscribe:
      message:
        $ref: '#/components/messages/MessageIn'
components: 
  messages: 
    MessageIn: 
      payload: 
        type: string
```

**Comment by jonaslagoni** [comment]
My personal opinion at the moment is that trying to support this outside of parameters is too complex and unnecessary. However, I completely agree we need better documentation and examples in the spec to show the user how to handle these scenarios.

My primary reasons for saying it is too complex:
- You would need to define something beyond https://datatracker.ietf.org/doc/html/rfc6570. 
- This behavior is NOT a standard.

In slack @gregmeldrum you wrote the following example:

> mytopic/{all} works for the * case, but the semantics of > are a little more problematic. The > equivalent would be mytopic/{all} and mytopic/{all}/{all} and mytopic/{all}/{all}/{all}  and so on. Unless there is a way to say {all} spans all remaining levels of the path.

To me when using AsyncAPI and you define `mytopic/{all}` and the protocol you are using is NATS (only protocol I know for sure supports it 😄) it is implied that when `>` is used, that it refers to this level and spans all remaining levels of the path. 

The reason it is implied is that we must remember, that it is entirely possible for protocols to define different behavior for what `>` and `*` means, there is no standard for it. So it all comes down to the context it is used.

### Why do I think that using parameters is enough?

Because of the way channels and parameters work in conjunction. The use-case for `>` and `*` for that matter (using NATS again), is because you want to use that special meaning "value" instead of a concrete value, and only specific systems support such special "values".

For example, you have two channels `mytopic/users/test` and `mytopic/operations/test` and you want one application to consume from both these channels. 

There are multiple ways to do this, or at least in NATS:
- You want to represent this by either `mytopic/{any}/test`, where `any` is the constant `*` value.
- Make use of the all value `mytopic/{all}`, where `all` is the constant `>` value.
- Describe it as `mytopic/{area}/test` where `area` can be either or `users` or `operations`. Much more fine-grained control. 

The only downside I foresee is that tooling has no way to know this behavior. For example, [Cupid](github.com/asyncapi/cupid) cannot automatically correlate `mytopic/{all}` with `mytopic/users/test` and `mytopic/operations/test`, at least not without intervention.

**Comment by jonaslagoni** [comment]
@gregmeldrum do you want to champion this? 🙂 Or can we consider this issue as needs champion? 🤔

**Comment by derberg** [comment]
@gregmeldrum @jonaslagoni is it something that would be part of `address` from the proposal of new 3.0 spec?
