### ISSUE TITLE
A message header to signal deprecation

### ISSUE THREAD

**Issue by sdatspun2** [asyncapi/spec#640]
Hello,

I would like to find out if there is a need to provide a message header (like correleationId, contentType) that indicates to the subscribers of a channel that a message is using deprecated schema (if schema-aware). For HTTP APIs, there is an HTTP header https://datatracker.ietf.org/doc/draft-ietf-httpapi-deprecation-header/ in pre-RFC stage to convey deprecation. I wonder a message header in case of AsyncAPI would be useful to provide. 

Thanks.
sanjay

**Comment by derberg** [comment]
@sdatspun2 AsyncAPI is a protocol-agnostic specification that you can use to describe any kind of event-driven architecture. Sometimes using HTTP protocol, sometimes WebSocket, etc. So there is no AsyncAPI specific property that you should add to message header to specify deprecation as it highly depends on the technology that you use. For example, if you follow CloudEvents (combined with AsyncAPI) spec for messages, they are working on introducing a property dedicated to depracation information -> https://github.com/cloudevents/spec/pull/787/files. I guess in other cases folks do not think in categories of deprecation information in a message but they deprecate entire channels/topics. 

Do you know what I mean? so it definitely highly depends IMHO on the protocol that you are using.

My assumption was you need it for technical reasons not to just render such information in docs.

**Comment by sdatspun2** [comment]
@derberg Deprecation of message payload (whole or part) is not protocol specific aspect imo. Am I missing something?

**Comment by derberg** [comment]
> OpenAPI's deprecated flag

yes, there is some discussion started but seems like there is not much interest -> https://github.com/asyncapi/spec/issues/305

> message header indicating deprecation would be useful

definitely, but why do you expect it to be a part of AsyncAPI? I mean, in the end, message and header can be described with different formats, like header in the end is a schema, message payload can be json schema, can be avro schema, and can also be an openapi schema. AsyncAPI enables you to use any schema you want and does not tell you what fields you should have there in your payload or headers. Does it make sense?

> Like correlationId

Yes, correlationId because of non standard approach to correlationId location and naming (some call it trackingId and I bet there are other names) has its individual place in the AsyncAPI file and works in the way that you specify there where someone can find info about correlationId. Main goal is tooling, so that tools have it easier to identify where given info is located.

So are you suggesting exactly the same for deprecation?

**Comment by sdatspun2** [comment]
@dret can you clarify about how to convey? in AsyncAPI doc or via a dedicated message header(s) at runtime?

>wouldn't it be simpler (and maybe an easier overall model) to simply
convey that the event is deprecated and may not be used in the future?

**Comment by dret** [comment]
On 2021-11-02 00:46, Sanjay Dalal wrote:
> @dret <https://github.com/dret> can you clarify about how to convey? in 
> AsyncAPI doc or via a dedicated message header(s) at runtime?
>     wouldn't it be simpler (and maybe an easier overall model) to simply
>     convey that the event is deprecated and may not be used in the future?

we have to separate the what and how. my proposal is to only deprecate 
that a message is deprecated, meaning that it will not be emitted 
anymore at some point in time.

the how part is tricky, as has been pointed out, because AsyncAPI is not 
addressing "bindings". the easiest way would be to at least support such 
a flag in AsyncAPI so that in marketplaces and other design-time places 
it would be clear that the message shouldn't be used anymore. if/how 
that could map to runtime mechanisms, i am not quite sure.

**Comment by dret** [comment]
this has been inactive for quite a while now but i think it might be useful to think about if/how message deprecation is supported in AsyncAPI. my gut feeling would be to see this as a possible flag at the message level ("you may see messages like this, but please don't build new components emitting these messages").
