### ISSUE TITLE
How do we define expected `schemaFormat` behavior in tooling?

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#656]
This issue is triggered by discussion in: https://github.com/asyncapi/spec/issues/622

How can we define a standard behavior (should we even define it?), to a degree that tooling can understand and implement "expected" behavior? 

I.e. if you are a maintainer on a parser, what do you do if you encounter a JSON Schema and a Raml schema that the message can follow? Especially if we talk about a mix such as what @GeraldLoeffler highlights in https://github.com/asyncapi/spec/issues/622#issuecomment-975746382.

In our [JS Parser](github.com/asyncapi/parser-js) we handle such different formats, by converting all of them to JSON Schema. However, this is highly up to interpretation as to how to achieve this. 

There are no standard conventions, tooling can follow to ensure that users of the spec get the "expected" output. 

Related issues
- https://github.com/asyncapi/spec/issues/655

**Comment by jonaslagoni** [comment]
Maybe this is something for https://github.com/asyncapi/parser-api to define? 🤔

**Comment by magicmatatjahu** [comment]
To be more specific, do you mean the conventions of how Avro/RAML/etc is to be converted to JSON Schema, yes?

**Comment by jonaslagoni** [comment]
> To be more specific, do you mean the conventions of how Avro/RAML/etc should be converted to JSON Schema, yes?

Not necessarily to JSON Schema, but how should tooling handle such logic in general. Should it even be converted to JSON Schema, or should it be something different?

This is especially needed when parsers in multiple languages are needed to ensure consistency between them.

**Comment by magicmatatjahu** [comment]
Ok, I understand, thanks! Atm ParserJS exactly converts the custom schemas to the AsyncAPI Schema Object (which is superset od JSON Schema, but it's not the same), so maybe we should go with that solution also in other implementations for another languages. However, in order to be consistent, we should have instructions on how to convert a given custom schema into an AsyncAPI Schema Object, i.e. what representation of the Raml, Avro etc keywords should be in the Schema Object - and this is where the `parser-api` repo would come in handy. Thanks for noticing the problem!

**Comment by jonaslagoni** [comment]
Still relevant

**Comment by magicmatatjahu** [comment]
@derberg Could you reopen it?
