### ISSUE TITLE
Ability to define a list of servers on which an operation is available

### ISSUE THREAD

**Issue by mgiovann** [asyncapi/spec#739]
## Problem

I want to represent that fact that my publish operation uses one URL (the URL of my message broker) and my subscribe operation uses another (the URL of my subscriber webhook).

## Suggestion

The operation object should allow an optional list of server object names on which the operation is available

Example:

```
asyncapi: '2.3.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
servers:
  prod-broker:
    url: 'https://message-broker.example.com/events'
    protocol: http
  prod-webhook-1:
    url: 'https://subscription-webhook.example.com/events'
    protocol: http
  prod-webhook-2:
    url: 'https://subscription-webhook.example.com/events'
    protocol: http    
channels:
  user/signedup:
    subscribe:
      servers: ['prod-webhook-1', 'prod-webhook-2']
      message:
        $ref: '#/components/messages/UserSignedUp'
    publish:
      servers: ['prod-broker']
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user   
```

**Comment by smoya** [comment]
Hi @mgiovann, thanks for your RFC submission!

I wonder if, for your use case, you could create two different channels instead and specify a different server on each through the `servers` field.
Am I guessing right if I say you considered but discarded it because your channel address is still the same on both servers (`user/signedup`)? 

AsyncAPI v3.0 will potentially include a big change in how Channels are identified. The address of the channel will be moved into a new field called `address` so you can have several channels pointing to the same address.
See  https://github.com/asyncapi/spec/issues/663. It might be the solution you are looking for?

**Comment by mgiovann** [comment]
Hi @smoya 

That proposal would seem to solve our issue. Thanks for bringing it to our attention.

**Comment by smoya** [comment]
Do you agree we can then close this issue @mgiovann ?

**Comment by magicmatatjahu** [comment]
It's just that two channels don't quite solve the problem, because then there is a duplication of data - even in the case of version 3. We are thinking that a channel is just an address, but it's also information about bindings, parameters etc. and copying a channel we usually have to do a lot of references which is not very friendly from the UX level. 

The ability to define servers at the level of operations is not such a strange idea and I would like to see it in the v3 version, of course, with a similar logic as with `channel.servers`:
- if `servers` are empty then the operation is available on every server
- if `servers` are not empty but `channel.servers` are empty then the operation is available on the servers in `operation.servers`
- if `servers` are not empty but also `channel.servers` are not empty then `operation.servers` must define servers from `channel.servers` as subset.
