### ISSUE TITLE
Linking AsyncAPI Spec to confluent Schema registry 

### ISSUE THREAD

**Issue by realmohan001** [asyncapi/spec#774]
I am trying to refer to AVRO schemas in confluent schema registry inside AsyncAPI spec. How do I provide the HTTP URL to confluent schema registry? Confluent Schema registry needs key/secret, Is there a place in ASyncAPI spec to provide it?

**Comment by dalelane** [comment]
@realmohan001 No - there isn't a dedicated place for it in the spec, although I have seen people embed it in the URL before as a workaround (e.g. `http://USERNAME:PASSWORD@schemaregistry-url` )

For what it's worth, in my opinion, I don't think credentials should go into an AsyncAPI doc  - in the same way that I wouldn't put REST API credentials in my OpenAPI docs. I use these documents to describe the auth mechanisms, but not to distribute credentials.

**Comment by dalelane** [comment]
> it is not working, because of the big secret value and its characters

I'm not sure exactly what you mean by this, but it sounds like perhaps you forgot to URL encode the strings.

> The intention was for code generation...

This is subjective, so I'm expressing my personal opinion here rather than saying how things should work. 

But personally, I wouldn't put username/password in my code - I keep credentials separate and external to my code, and provide them at run-time through things like environment variables. 

That said, I absolutely think the code generation could do more to encourage this (e.g. adopt a naming convention for environment variables and generate code that checks for credentials in env vars with those names) and make this easier - rather than leaving us to add that when we tweak the starting point the generators create.

**Comment by realmohan001** [comment]
@dalelane : Thank you that was the issue. I had to URl encode the key/secret, as it has special characters.
