### ISSUE TITLE
Adding some new tools to the list

### ISSUE THREAD

**Issue by jemacineiras** [asyncapi/spec#814]
Hi community,

here at Corunet by Sngular are developing some interesting tools using your awesome specification. They are close to mature, so we want to share them with you. If you consider them interesting to add them to your available tool list, we will be pleased.

Maven plugin to generate Spring cloud stream code base on Asyncapi and OpenApi
https://github.com/corunet/scs-multiapi-plugin

Maven plugin to generate Spring cloud Contracts base on Asyncapi and OpenApi
https://github.com/corunet/scc-multiapi-converter

Cheers

**Comment by magicmatatjahu** [comment]
@jemacineiras Hi! We are happy with these projects! If you wanna add them to our list, you should update that md file and create PR https://github.com/asyncapi/website/blob/master/pages/docs/tools/index.md Let me know if you will have any problems :) Of course, if you won't find appropriate category, please create the new one.

**Comment by fmvilas** [comment]
Side comment: really cool to see my fellow Spanish devs contributing to AsyncAPI 🙌

**Comment by jemacineiras** [comment]
Hi @akshatnema,

The proposed solution looks interesting, if the tool is only using asyncapi, but in our case, our tools give support for openapi and asyncapi, and we don't like to attach the project to only one API solution, just in case openapi decide the same, or we want to integrate future solutions...

So we prefer the second approach, what your thoughts about?

Cheers!

**Comment by akshatnema** [comment]
Fine, thanks for your feedback. So, if you prefer the second approach, you need to add the details of your tool in a markdown file in the website in the website, with the appropriate technologies used and the links of the tool. That markdown information will be converted to JSON and then rendered on the website as other tools. Right now, the format of the markdown file has not been decided yet and we are proceeding with the first approach right now.

The reason why we primarily focus on first is that we want the tools to be discovered automatically using API searching instead of manually adding them to the website repository. Hence, we are forwarding that. @derberg, anything more you want to add?
