### ISSUE TITLE
Permit declaration of permitted TLS cipher suites for connections

### ISSUE THREAD

**Issue by philCryoport** [asyncapi/spec#849]
It would be really helpful if we could declare in our AsyncAPI spec which TLS cipher suites are permitted for connections so there is no confusion when MQTT clients are implemented.

For example, [here's AWS IoT's official list of permitted TLS cipher suites](https://docs.aws.amazon.com/iot/latest/developerguide/transport-security.html#tls-cipher-suite-support).

The theory is then that the code-generators would then only use connection libraries that support one or more of the specified TLS cipher suites -- and would configure the generated code to specifically use the specified cipher suites.

Please consider?

Thanks.

**Comment by derberg** [comment]
@philCryoport hey, thanks for the issue.

Can you provide more clarification.
So you need option on each `server` to specify `cipher suite` right? its name?

Is there so official AWS independent list of those? some organization managing these?

**Comment by philCryoport** [comment]
> Can you provide more clarification. So you need option on each `server` to specify `cipher suite` right? its name?
> 
> Is there so official AWS independent list of those? some organization managing these?

Hi @derberg not sure what you mean by your question.

Here, let me give my specific use case:

I'd like to specify in an AsyncAPI schema that the only acceptable TLS cipher suites for communicating with a server are:
* ECDHE-ECDSA-AES128-GCM-SHA256
* ECDHE-RSA-AES128-GCM-SHA256
(...or for a set of servers within this AsyncAPI schema file...or across all servers in this entire AsyncAPI schema file...)

Why am I picking those?  Because those are AWS IoT's recommended TLS cipher suites.

Is there a way to do that?  Does it make sense to do that?

**Comment by derberg** [comment]
@philCryoport sorry for not being specific. I'm not an expert in security in the case of TLS when you say cipher suite, you basically mean encryption used to generate the certificate. 

If I'm right, isn't it enough to specify this -> https://www.asyncapi.com/docs/reference/specification/v2.5.0#x509-authentication-sample

When you generate a client, you do not generate certificates at the same time, right? you just pass them on? or is there something code specific that needs to be set depending on used cipher suite?

sorry for late response, we were occupied last 2 weeks because of AsyncAPI Conf that tool place last week

**Comment by philCryoport** [comment]
Hi @derberg no worries.  I missed the conference taking care of my ill child.  Hope you had a good conference -- and the sessions will be posted to YouTube.

I'll stick with what you propose.  Thanks for the reply back.

**Comment by derberg** [comment]
@philCryoport thanks. Btw, almost all recordings are [here](https://www.youtube.com/playlist?list=PLbi1gRlP7pijRiA32SU36hD_FW-2qyPhl) already. Enjoy ☺️
