### ISSUE TITLE
Binary-encoded message as response

### ISSUE THREAD

**Issue by fgadaleta** [asyncapi/spec#891]
How would one go adding a binary-encoded message as a response from a `subscribe`? 
As a matter of fact, a `subscribe` can return a `subscribeStatus` message. 
The messages that are pushed by the server over the socket depend on the e.g. topic one subscribed to. 
If those messages are binary encoded (for performance reason), how would one go documenting this scenario?  

**Example**

Client subscribes to a channel requesting a series of sensor data
Server is optimizing such request and packing in an array the values of 10 sensors in binary format

Client will start receiving a stream of data `(timestamp, <array>)` and will unpack accordingly

**Comment by jonaslagoni** [comment]
It's a good question, cause there is almost no support for encodings other than JSON, at least from a tooling perspective. Do you have any specifics in mind @fgadaleta?

**Comment by fgadaleta** [comment]
I would definitely describe the format of the binary message on a byte level (at least). This would allow one to generate examples automatically and more importantly to know how to deserialize the chunk.

e.g.

```
byte pos.   | 0 - 3 | 3 - 4 | 4 - 11| 
data type   | uint  | char  | double|
``` 

Maybe this can be described via a json?

```
{
    [
     "start": 0,
     "end": 3:
     "type": uint
    ],
    ...
}
```

**Comment by jonaslagoni** [comment]
@fgadaleta I guess the dilemma is that even if you define the content type defines the payload as arbitrary binary data

```json
{
  "asyncapi": "2.5.0",
  ...
  "defaultContentType": "application/octet-stream"
}
```

you would like to define that format in more detail? 🤔 Or do you just want tools to give you the possibility to add this custom binary serialization and deserialization? Or both?

**Comment by fgadaleta** [comment]
I think one should have both. 
If you can't define what's in that binary, it's useless. 
Maybe giving the possibility to define an opaque binary (just a chunk of N bytes) and a transparent way for developers to consume that binary in the right way.

**Comment by jonaslagoni** [comment]
Yea that makes sense.

There is no standardized ways to do this, however, it is achievable without waiting for the spec to change, here is how: I would first start with specifying my binary format in the spec with the use of extensions:

```js
{
  "asyncapi": "2.5.0",
  ...
  "defaultContentType": "application/octet-stream"
  "x-binaryFormat": { ... } // Add your own interpretation here that you think makes sense, or use existing standard.
}
```

I would then want to generate models that correctly uphold this binary format, here I would use Modelina because it enables the customization you need and reusability across AsyncAPI documents. In Modelina I would add my own custom serialization and deserialization functions:

```js
const input = ...;
const generator = new PythonGenerator({
  presets: [{
    class: {
      additionalContent(args) {
        return `${args.content}
def custom_binary_serialize(self):
  ...

@staticmethod
def custom_binary_deserialize(bytes):
  ...
`;
      },
    }
  }]
});
```

You can read more about presets [here](https://github.com/asyncapi/modelina/blob/next/docs/presets.md).

This gives you a couple of benefits:
1. The presets for Modelina can be contributed to the core project for others to use as well, as they are easily sharable. And we actually don't have any binary serialization yet, so it would be perfect!
2. Once supported in Modelina, it more easily gives code templates the option to support it natively as well.
3. The specification extension you use can form the beginning of an [RFC](https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md#rfc-contribution-champions) to help others do exactly the same!

Hope that helps!
